controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - left_finger_joint
      - right_finger_joint
initial:  # Define initial robot poses per group
  - group: arm
    pose: zeros
  - group: hand
    pose: open_hand