# MoveIt-specific simulation settings
moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
    joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6
        - right_finger_joint
        - left_finger_joint
    sim_control_mode: 0  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
arm_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6

    gains:
        joint_1: { p: 1000000, d: 3, i: 10, i_clamp: 1 }
        joint_2: { p: 1200000, d: 3, i: 10, i_clamp: 1 }
        joint_3: { p: 80000, d: 3, i: 10, i_clamp: 1 }
        joint_4: { p: 5000, d: 3, i: 10, i_clamp: 1 }
        joint_5: { p: 500, d: 3, i: 10, i_clamp: 1 }
        joint_6: { p: 500, d: 3, i: 10, i_clamp: 1 }

    constraints:
        goal_time: 1.0
    state_publish_rate: 25

hand_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
        - right_finger_joint
        - left_finger_joint
    gains:
        right_finger_joint: { p: 500, d: 3.0, i: 10, i_clamp: 1 }
        left_finger_joint: { p: 500, d: 3.0, i: 10, i_clamp: 1 }

    state_publish_rate: 25

controller_list:
    - name: arm_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6

    - name: hand_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - right_finger_joint
        - left_finger_joint
