# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.9 #0.1
default_acceleration_scaling_factor: 0.9 #0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 5 #2.268928027592628
    has_acceleration_limits: false
    max_acceleration: 4 #0
  joint_2:
    has_velocity_limits: true
    max_velocity: 4.5 #2.007128639793479
    has_acceleration_limits: false
    max_acceleration: 3 #0
  joint_3:
    has_velocity_limits: true
    max_velocity: 4.5 #2.181661564992912
    has_acceleration_limits: false
    max_acceleration: 3 #0
  joint_4:
    has_velocity_limits: true
    max_velocity: 4.5 #3.141592653589793
    has_acceleration_limits: false
    max_acceleration: 3 #0
  joint_5:
    has_velocity_limits: true
    max_velocity: 4.5 #3.141592653589793
    has_acceleration_limits: false
    max_acceleration: 3 #0
  joint_6:
    has_velocity_limits: true
    max_velocity: 6 #4.537856055185257
    has_acceleration_limits: false
    max_acceleration: 3 #0
  left_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: false
    max_acceleration: 0.5
  right_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: false
    max_acceleration: 0.5